# key words
- impute: SimpleImputer

In [1]:
import numpy as np

from sklearn import datasets
from sklearn import impute

iris = datasets.load_iris()
iris_X = iris.data

# init mask array randomly
masking_array = np.random.binomial(1, .25, iris_X.shape).astype(bool)
print(masking_array[:5])

iris_X[masking_array] = np.nan
print(iris_X[:5])

# impute missing values through various strategies
for strategy in ['mean', 'median']:
    imputer = impute.SimpleImputer(missing_values=np.nan, strategy=strategy)
    iris_X_prime = imputer.fit_transform(iris_X)
    print("strategy = [%s]\n%s" % (strategy, iris_X_prime[:5]))

[[False False False False]
 [False False False False]
 [False False False  True]
 [False  True False  True]
 [False False  True False]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 nan]
 [4.6 nan 1.5 nan]
 [5.  3.6 nan 0.2]]
strategy = [mean]
[[5.1        3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [4.7        3.2        1.3        1.24485981]
 [4.6        3.07586207 1.5        1.24485981]
 [5.         3.6        3.72016807 0.2       ]]
strategy = [median]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 1.3]
 [4.6 3.  1.5 1.3]
 [5.  3.6 4.2 0.2]]
