In [1]:
import numpy as np
import math
import os
import uuid
import graphviz
import matplotlib.pyplot as plt

In [54]:
def g(X, val, op):
    if op == 1:
        # 1: X > val, 0: X = val, -1: X < val
        return np.sign(X - val)
    else:
        # 1: X < val, 0: X = val, -1: X > val
        return np.sign(val - X)

m = 10
n = 1

X = np.arange(m).reshape((m, n))
y = np.array([1, 1, 1, -1, -1, -1, 1, 1, 1, -1])
w = np.ones(m) / m
sps = (X[:-1, 0] + X[1:, 0]) / 2
ops = np.ones(m - 1)
ers = np.ones(m - 1)

for i, s in enumerate(sps):
    ers[i] = np.sum(w * (g(X[:, 0], s, ops[i]) != y))
    if ers[i] > 0.5:
        ops[i] = - ops[i]
        ers[i] = 1. - ers[i]
    print(i, ops[i], 'sp =', sps[i], 'er =', ers[i])

# choose 3 weak classifier as G1~G3
epoches = 100
m_func = 3
rk3_idx = np.argsort(ers)[:m_func]
sps = sps[rk3_idx]
ops = ops[rk3_idx]

for i in range(3):
    print(i, ops[i], sps[i])

for epoch in range(epoches):
    ers = np.ones(m_func)
    for i, s in enumerate(sps):
        ers[i] = np.sum(w * (g(X[:, 0], s, ops[i]) != y))
    
    print(ers)
    idx = np.argsort(ers)[0]
    print('idx', idx)
    
# # er = 1.
# epsilon = 1e-10
# # idx = 0

    a = 1 / 2 * np.log((1 - ers[idx] + epsilon) / (ers[idx] + epsilon))
    print(epoch, 'a', a)
    z = np.sum(w * np.exp(- a * y * g(X.ravel(), sps[idx], ops[idx])))
    print(epoch, 'z', z)
    w = w / z * np.exp(- a * y * g(X.ravel(), sps[idx], ops[idx]))
    print(epoch, 'w', w)

0 1.0 sp = 0.5 er = 0.5
1 -1.0 sp = 1.5 er = 0.4
2 -1.0 sp = 2.5 er = 0.29999999999999993
3 -1.0 sp = 3.5 er = 0.4
4 1.0 sp = 4.5 er = 0.5
5 1.0 sp = 5.5 er = 0.4
6 1.0 sp = 6.5 er = 0.5
7 -1.0 sp = 7.5 er = 0.4
8 -1.0 sp = 8.5 er = 0.30000000000000004
0 -1.0 2.5
1 -1.0 8.5
2 -1.0 1.5
[0.3 0.3 0.4]
idx 0
0 a 0.42364893009836363
0 z 0.9165151389911682
0 w [0.07142857 0.07142857 0.07142857 0.07142857 0.07142857 0.07142857
 0.16666667 0.16666667 0.16666667 0.07142857]
[0.5        0.21428571 0.57142857]
idx 1
1 a 0.6496414918348274
1 z 0.8206518066767104
1 w [0.04545455 0.04545455 0.04545455 0.16666667 0.16666667 0.16666667
 0.10606061 0.10606061 0.10606061 0.04545455]
[0.31818182 0.5        0.36363636]
idx 0
2 a 0.38107002586598815
2 z 0.9315409787485485
2 w [0.03333333 0.03333333 0.03333333 0.12222222 0.12222222 0.12222222
 0.16666667 0.16666667 0.16666667 0.03333333]
[0.5        0.36666667 0.53333333]
idx 1
3 a 0.2732718531574227
3 z 0.9637888196454804
3 w [0.02631579 0.02631579 0.02631